apiVersion: v1
kind: Service
metadata:
  name: rmm-agent-service
spec:
  type: NodePort
  selector:
    app: rmm-agent
    version: green
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
